drop table if exists nsi.loc_koef_kpd_diff_speed;

create table nsi.loc_koef_kpd_diff_speed
(
	id serial not null,
	v real,
	kpd real
);

comment on table nsi.loc_koef_kpd_diff_speed is 'КПД для электропоездов постоянного, переменного тока при различных скоростях движения, КПД АМВПС при различных скоростях движения';
comment on column nsi.loc_koef_kpd_diff_speed.v is 'Скорость движения, км./ч.';
comment on column nsi.loc_koef_kpd_diff_speed.kpd is 'КПД, %';

create index loc_koef_kpd_diff_speed_id_index
	on nsi.loc_koef_kpd_diff_speed (id);

insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 5, 18.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 10, 36.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 20, 73.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 22.5, 79.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 25, 84.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 30, 84.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 35, 85.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 40, 88.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 45, 86.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 50, 86.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 55, 87.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 60, 87.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 65, 83.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 70, 88.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 80, 89.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 90, 89.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 100, 88.0);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 110, 87.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (1, 120, 86.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 5, 13.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 10, 26.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 20, 52.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 30, 78.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 31.8, 83.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 35, 85.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 39.2, 87.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 40, 86.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 45, 87.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 50, 88.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 52, 88.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 55, 91.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 59.8, 90.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 60, 89.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 65, 85.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 70, 86.0);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 80, 90.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 90, 90.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 100, 88.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 110, 89.0);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (2, 120, 90.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 5, 13.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 10, 31.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 28, 88.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 40, 90.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 42, 92.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 45, 92.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 50, 92.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 53, 91.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 55, 90.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 60, 90.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 65, 91.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 70, 92.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 74, 92.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 75, 91.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 80, 91.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 85, 89.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 90, 87.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 100, 84.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 110, 82.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (3, 120, 84.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 5, 26.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 10, 51.0);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 15, 80.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 20, 89.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 25, 94.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 30, 92.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 34, 92.0);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 42, 93.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 45, 92.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 50, 93.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 55, 93.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 60, 94.0);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 63.2, 93.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 70, 95.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 80, 93.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 90, 89.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 100, 87.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 110, 84.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (4, 120, 84.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 10, 62);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 20, 75);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 30, 80);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 40, 83);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 50, 85);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 60, 87);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 70, 88);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 80, 88.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 90, 89);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 100, 89);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 110, 89);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 120, 89);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 130, 88.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 140, 88.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 150, 87.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (5, 160, 87);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (6, 10, 74.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (6, 20, 80.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (6, 30, 82.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (6, 40, 83.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (6, 50, 86.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (6, 60, 86.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (6, 70, 85.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (6, 80, 85.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (6, 90, 85.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (6, 100, 86.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (6, 120, 85.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 10, 61.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 20, 73.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 30, 79.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 40, 82);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 50, 83.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 60, 85.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 70, 86);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 80, 87.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 90, 88);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 100, 88.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 125, 89.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 150, 90);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 200, 90);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (7, 250, 90);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 5, 51.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 10, 62.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 15, 68.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 20, 72.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 22, 77);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 25, 73.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 30, 77.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 35, 80.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 37.5, 82.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 40, 80.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 42.5, 82.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 45, 84.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 50, 84.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 60, 85);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 70, 88.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 80, 88.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 90, 86.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 100, 85.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (8, 110, 84.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 5, 52.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 10, 71.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 20, 84.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 30, 87.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 36.1, 85.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 37.9, 85.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 40.6, 86.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 44, 86.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 48.9, 87);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 55.6, 87.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 56.6, 87.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 59, 87.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 64.6, 88.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 72.3, 88.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 85.9, 89.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 91.7, 90.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 100, 90.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (9, 120, 91.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (10, 10, 56.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (10, 20, 73.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (10, 30, 80.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (10, 40, 85.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (10, 43.5, 86.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (10, 50, 85.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (10, 60, 83.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (10, 70, 84.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (10, 80, 87);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (10, 90, 87);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (10, 100, 87);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (10, 120, 87);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 10, 60);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 20, 72);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 30, 77);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 40, 80);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 50, 82.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 60, 84);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 70, 85);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 80, 86);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 90, 86);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 100, 86);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 110, 86);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 120, 86);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 130, 86);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 140, 86);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 150, 85.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (11, 160, 85);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 10, 61.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 20, 72.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 30, 77.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 40, 80.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 50, 82.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 60, 83.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 70, 83.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 80, 84.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 90, 85.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 100, 85.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 125, 86.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 150, 86.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 200, 87);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (12, 250, 87);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (13, 10, 10.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (13, 20, 17.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (13, 30, 21);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (13, 40, 23.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (13, 50, 25);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (13, 60, 26.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (13, 70, 26.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (13, 80, 27.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (13, 90, 26.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (13, 100, 27.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (13, 110, 27.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (13, 120, 27.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (14, 5, 8.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (14, 10, 15.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (14, 20, 23.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (14, 30, 27.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (14, 40, 27.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (14, 50, 27.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (14, 60, 27.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (14, 70, 27.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (14, 80, 27.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (14, 90, 27.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (14, 100, 26.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (14, 110, 26.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (14, 120, 25.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (15, 5, 8.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (15, 10, 15.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (15, 20, 23.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (15, 30, 27.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (15, 40, 27.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (15, 50, 27.9);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (15, 60, 27.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (15, 70, 27.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (15, 80, 27.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (15, 90, 27.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (15, 100, 27.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (15, 110, 26.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (15, 120, 25.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (16, 5, 8.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (16, 10, 15.1);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (16, 20, 22.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (16, 30, 25.3);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (16, 40, 26);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (16, 50, 25.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (16, 60, 24);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (16, 70, 26.2);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (16, 80, 29.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (16, 90, 28.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (16, 100, 27.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (17, 5, 8.4);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (17, 10, 14.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (17, 20, 22);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (17, 30, 24.7);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (17, 40, 25.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (17, 50, 25.8);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (17, 60, 24.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (17, 70, 25.15);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (17, 80, 28.5);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (17, 90, 28.6);
insert into nsi.loc_koef_kpd_diff_speed(id, v, kpd) values (17, 100, 27.9);

alter table nsi.loc_ser
	add id_koef_kpd_diff_speed integer;
comment on column nsi.loc_ser.id_koef_kpd_diff_speed is 'Ссылка на id таблицы nsi.loc_koef_kpd_diff_speed';

update nsi.loc_ser set id_koef_kpd_diff_speed=1 where num_ser in (306, 366, 313, 371, 372);
update nsi.loc_ser set id_koef_kpd_diff_speed=2 where num_ser in (318, 316, 322, 324);
update nsi.loc_ser set id_koef_kpd_diff_speed=3 where num_ser in (328, 310);
update nsi.loc_ser set id_koef_kpd_diff_speed=4 where num_ser in (323);
update nsi.loc_ser set id_koef_kpd_diff_speed=5 where num_ser in (486, 317, 377, 488);
update nsi.loc_ser set id_koef_kpd_diff_speed=6 where num_ser in (375);
update nsi.loc_ser set id_koef_kpd_diff_speed=7 where num_ser in (309);
update nsi.loc_ser set id_koef_kpd_diff_speed=8 where num_ser in (401, 402, 405, 406, 410, 409, 404, 403);
update nsi.loc_ser set id_koef_kpd_diff_speed=9 where num_ser in (412, 413);
update nsi.loc_ser set id_koef_kpd_diff_speed=10 where num_ser in (416, 425);
update nsi.loc_ser set id_koef_kpd_diff_speed=11 where num_ser in (488);
update nsi.loc_ser set id_koef_kpd_diff_speed=12 where num_ser in (482);
update nsi.loc_ser set id_koef_kpd_diff_speed=13 where num_ser in (802);
update nsi.loc_ser set id_koef_kpd_diff_speed=14 where num_ser in (804);
update nsi.loc_ser set id_koef_kpd_diff_speed=15 where num_ser in (705);
update nsi.loc_ser set id_koef_kpd_diff_speed=16 where num_ser in (852);
update nsi.loc_ser set id_koef_kpd_diff_speed=17 where num_ser in (851);

