//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.30 at 02:58:34 PM MSK 
//


package loader.comm.model.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the loader.comm.model.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: loader.comm.model.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Z63LASEREPORTGETOPER }
     * 
     */
    public Z63LASEREPORTGETOPER createZ63LASEREPORTGETOPER() {
        return new Z63LASEREPORTGETOPER();
    }

    /**
     * Create an instance of {@link Z63LASEREPORTGETOPERResponse }
     * 
     */
    public Z63LASEREPORTGETOPERResponse createZ63LASEREPORTGETOPERResponse() {
        return new Z63LASEREPORTGETOPERResponse();
    }

    /**
     * Create an instance of {@link Z63LASEREPORTGETNSI }
     * 
     */
    public Z63LASEREPORTGETNSI createZ63LASEREPORTGETNSI() {
        return new Z63LASEREPORTGETNSI();
    }

    /**
     * Create an instance of {@link Z63LASEREPORTGETNSIResponse }
     * 
     */
    public Z63LASEREPORTGETNSIResponse createZ63LASEREPORTGETNSIResponse() {
        return new Z63LASEREPORTGETNSIResponse();
    }

}
